language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
  fast_finish: true

before_install:
  - composer selfupdate

install:
  - composer update --no-progress --profile --prefer-dist --no-scripts --no-interaction
  - composer show

script:
  - ./vendor/bin/phpunit --verbose
